### ISSUE TITLE
Release Arm64 Images Too

### ISSUE THREAD

**Issue by Shabinder** [andreee94/cert-manager-webhook-freenom#2]
Please If possible build and release arm64 images alongside amd64 too

**Comment by andreee94** [comment]
In the next days I will try to build the image for the arm64 architecture, but unfortunately I do not have an ARM kubernetes cluster on which to test it.
In that case, are you able to check if it works?

**Comment by andreee94** [comment]
Starting from version 0.5.0 the ARM64 version is now included in the docker image building process by github actions. 
You can get it both from dockerhub and github container registry.

Let me know if you may test it.

**Comment by michbeck100** [comment]
The arm64 image does not exist for version 0.6.0
